### ISSUE TITLE
Provide Generator instance for NoContentVerb combinator

### ISSUE THREAD

**Issue by jhrcek** [3kyro/servant-benchmark#1]
Hello.
Interesting project you have here :smile: 
While playing with it I stumbled upon the missing type family instance of Generator for [NoContentVerb](https://hackage.haskell.org/package/servant-0.18.2/docs/Servant-API.html#t:NoContentVerb) combinator.
To reproduce just try to create generator for api like this:

```haskell
"projects" :> Capture "project-id" ProjectId :> DeleteNoContent
```

I wanted to add the instance myself, but now I'm not sure if it's even a good idea that this library is using closed type family to represent Generator (given the "open" nature of servant API, which should allow users adding their own combinators). Any thoughts on this?

**Comment by 3kyro** [comment]
Hi, thanks for the issue :)

You are right about using an open type family for `Generator`. Actually it was an early decision for avoiding overlapping instances, but as you mention this will restrict users from using their own combinators. I'll push a PR to make the change. If you'd still like to add the instance for `NoContentVerb` please let me know, otherwise I'll follow up with this as well.

**Comment by jhrcek** [comment]
Thank you, using open type family makes sense.
I'll try to add the instance myself and create a PR later today just to practice some OSS contributions :)

**Comment by 3kyro** [comment]
Thanks again for the PR 👍🏽
